### ISSUE TITLE
Checking own vs others balances permissions.

### ISSUE THREAD

**Issue by skulltraill** [MichaelFedora/FedorasEconomy#2]
Hey,

I noticed on the wiki, it shows the same permission node for /balance (for oneself) and /balance <user> (check other peoples' balances).

I would like users to be able to check their own balance, but not view other peoples' balances.

Is this possible? If not, could you implement it?

Thanks.

**Comment by MichaelFedora** [comment]
I can definitely look into it.

**Comment by MichaelFedora** [comment]
`fedoraseconomy.global.balance.other` is the perm your looking for! In v1.1.2, which can be found [here](https://github.com/MichaelFedora/FedorasEconomy/releases/tag/1.1.2).
